### ISSUE TITLE
Allow Plans to apply to multiple repositories

### ISSUE THREAD

**Issue by jlantz** [SalesforceFoundation/MetaCI#124]
There are now many plans in our production instance which duplicate everything except the repository they target.  It would be far easier to maintain plans that can apply to multiple repositories with the same config.  If an individual project needed a custom version of the plan, it would be unlinked from the shared plan's `repositories` field and a new Plan with the same configuration would be manually created targeting only that repository with the config customizations it requires.

**Comment by cdcarter** [comment]
this is done!
