### ISSUE TITLE
Enable repo filtering for plan notifications

### ISSUE THREAD

**Issue by cpolcyn** [SalesforceFoundation/MetaCI#194]
Plan Notifications currently do not allow filtering by repo. So if a plan is associated to multiple repos, the plan notification will trigger for all the associated repos.

We should have an option to limit the notification to a particular repo. Default would be to notify for all associated repos.

**Comment by ceiroa** [comment]
Also the UI on this is confusing, as it lists the same plan multiple times:

![screen shot 2018-03-02 at 2 56 56 pm](https://user-images.githubusercontent.com/1894238/36921466-1aeb4f50-1e2a-11e8-941d-cbeca0870efe.png)

**Comment by cpolcyn** [comment]
@ceiroa those are actually separate plans that happen to have the same name. We should update the model name method to use the object ID as well to ensure uniqueness.

**Comment by cdcarter** [comment]
i think we need to have a little convocation on plans/plan naming/our public and private plan split - its definitely confusing in other places too.

**Comment by cpolcyn** [comment]
addressed in https://github.com/SalesforceFoundation/MetaCI/pull/206
