### ISSUE TITLE
document New Org Please 

### ISSUE THREAD

**Issue by cdcarter** [SalesforceFoundation/MetaCI#226]
write user documentation for New Org Please page and expected behavior

**Comment by annejackson** [comment]
@cdcarter  here is the rough draft of what I have written up for onboarding so far:
* Scratch Org Creation process on Meta Ci:  
    * In MrbelvedereCi:  https://mrbelvedereci.herokuapp.com/plans/new_org_please/
    * Go to the appropriate Plan (project) and Repo/Flow you need to test your ticket/Pull Request and click the “*Go*” button from that line.
    * Choose the appropriate branch for the pull request you are testing  (see below screenshot on how your PR branch is named).  The Commit field stays blank. And leave the “Keep Org” checkbox selected (the scratch org will last for the default 7 days). Click “*Submit*” button. 
    * Keep refreshing your browser to see the progress of your scratch org building, and when it's done there will be a Status of Success in green on the top left. (Sometimes you  might have to wait an additional 5 or so minutes for the DNS portion to get registered). 
    * Once it's done, go to the Org tab and then Click the “*Log In*” button. A new tab in your browser will open up your Org. When you are done with it, make sure to Delete the scratch org. 
    * You can find all your current scratch orgs created by this process on your Github profile page (where you can also Login or Delete them):
        https://mrbelvedereci.herokuapp.com/users/GitHubUsernameHere/

![branch](https://user-images.githubusercontent.com/35311289/37978112-4351de2c-31b3-11e8-8aae-ea154f7a084f.png)

**Comment by annejackson** [comment]
@cdcarter - I think you did this already and it looks good! :) You should totally close it!
