### ISSUE TITLE
Profile page: If scratch orgs expire before a user deletes them there are some issues

### ISSUE THREAD

**Issue by annejackson** [SalesforceFoundation/MetaCI#230]
This is on the profile page in MetaCI.

I had some scratch orgs that are way past the 7 day expiration and I forgot to delete them. They still show on my profile page.

Also, The login/delete buttons don't work for scratch orgs that are expired. see screenshot. 

![expired scratch orgs](https://user-images.githubusercontent.com/35311289/38379648-4e4ccf9e-38cf-11e8-959c-3a151e341b0c.png)

**Comment by annejackson** [comment]
fyi @cdcarter

**Comment by cdcarter** [comment]
fixed in #231 which will go to production today or tomorrow.

scratch orgs created from now on will remove themselves from the list when expired. existing scratch orgs will not be auto-deleted, but clicking "delete" will either delete the org, or mark it as expired if it already is.
