### ISSUE TITLE
Automatically add new repositories/plans onto the Create Scratch Org Please page (Abacus project needs added)

### ISSUE THREAD

**Issue by annejackson** [SalesforceFoundation/MetaCI#258]
Was curious if there was a way for this process to be automated somehow and show available projects/plans on the create scratch org please page by default??

Also, can we get the new Abacus project with a dev_org flow added to the meta ci create scratch org please page?
Example of Pull request.
https://github.com/SalesforceFoundation/Abacus/pull/1

After that possibly Multiple Tributes, but I don't think we are sure about that one yet.

Fyi @cdcarter  and @jlantz

**Comment by cdcarter** [comment]
Hi @annejackson, since this is related to configuration for an internal product, please open a WI under the RelEng - Admin work item.
