### ISSUE TITLE
Scratch org login not working

### ISSUE THREAD

**Issue by cpolcyn** [SalesforceFoundation/MetaCI#40]
Try to log in to an org using the "Log In" button on org tab of build detail view, encounter error 500.

**Comment by cpolcyn** [comment]
cannot reproduce locally

**Comment by cpolcyn** [comment]
```json
{
  "message":"No org configuration found for name test-4x6htt3tkkdm@cumulusci-test_dev_workspace.net",
  "status":1,
  "name":"NoOrgFound",
  "action":"Run the \"sfdx force:auth\" commands with --setdefaultusername to connect to an org and set it as your default org.\nRun \"force:org:create\" with --setdefaultusername to create a scratch org and set it as your default org.\nRun \"sfdx force:config:set defaultusername=<username>\" to set your default username."
}
```

**Comment by cpolcyn** [comment]
Seems to only occur with scratch orgs. When logging into persistent orgs the problem is that user is left at login.salesforce.com but not logged in.

**Comment by cpolcyn** [comment]
https://sentry.io/salesforceorg/mrbelvedereci/issues/314998888/

**Comment by cdcarter** [comment]
for persistent orgs:

login just redirects to OrgConfig.start_url - without refreshing the token before hand. this means we try to login with whatever SID is in the json in the DB, and not a valid token.

**Comment by cpolcyn** [comment]
Login to persistent orgs seems to be working now as of 6eb0ffb57e5bcd08c50de36580fdedb63a957c0e. Login for scratch orgs still shows 500 Internal Error on the mrbelvedereci org login page.

**Comment by cpolcyn** [comment]
When the logged in user presses the button to log in to a scratch org, the user is logged out of the mrbelvedereci app.

**Comment by cpolcyn** [comment]
`sfdx force:org:list --all` on heroku app shows 2 dev hubs (1 is default) and no scratch orgs.

**Comment by cpolcyn** [comment]
We already prevent log-in to scratch orgs via the org detail view:
https://github.com/SalesforceFoundation/mrbelvedereci/blob/master/mrbelvedereci/cumulusci/templates/cumulusci/org_detail.html#L29

**Comment by cpolcyn** [comment]
@jlantz any ideas on this one?

**Comment by cdcarter** [comment]
is this because the web dyno has a different .sfdx folder than the workers?
