### ISSUE TITLE
Rebuild incomplete builds on startup

### ISSUE THREAD

**Issue by cpolcyn** [SalesforceFoundation/MetaCI#53]
If the site goes down while builds are incomplete (queued/waiting/running) those builds would be stuck like that so we have to manually rebuild. We should add a process to run right after the main dyno starts up that would check the database for these builds and rebuild automatically.

**Comment by jlantz** [comment]
This is *supposed* to do that for us already:
https://github.com/SalesforceFoundation/mrbelvedereci/blob/master/mrbelvedereci/build/worker.py

The other challenge is that there is no "main dyno", there's the web dyno, the worker-short dyno, the scheduler dyno, and the worker dynos.  The worker-short would be the logical place for this to live but simply when that one restarts isn't a good way to do it as it might restart on its own while the worker dynos are still running their builds.

**Comment by cpolcyn** [comment]
addressed in https://github.com/SalesforceFoundation/MetaCI/pull/216
